name: Run Tests and Generate report
on:
    workflow_dispatch:
        push:
            branches:
                - 'main' # (main branch) Set branch of the GH repo to push
jobs:
    test_suite: # Name of the job
        runs-on: ubuntu-latest # Choosing OS
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.18.2' # In command line run “node -v” and choose your version
            - run: npm ci
            - name: Run tests
              run: npm run test:chrome:headless # Our name of the headless script
            - name: Generate Report
              if: always()
              run: npm run allure:generate # Name of the allure generate script
            - name: Upload artifact allure-report
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: allure-report
                  path: ./allure-report
